/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginRegisterImport } from './routes/login-register'
import { Route as ChartsImport } from './routes/charts'
import { Route as DashboardLayoutImport } from './routes/_dashboardLayout'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardLayoutUploadExpenseImport } from './routes/_dashboardLayout/upload-expense'
import { Route as DashboardLayoutTagsImport } from './routes/_dashboardLayout/tags'
import { Route as DashboardLayoutDashboardImport } from './routes/_dashboardLayout/dashboard'

// Create/Update Routes

const LoginRegisterRoute = LoginRegisterImport.update({
  path: '/login-register',
  getParentRoute: () => rootRoute,
} as any)

const ChartsRoute = ChartsImport.update({
  path: '/charts',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutUploadExpenseRoute =
  DashboardLayoutUploadExpenseImport.update({
    path: '/upload-expense',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutTagsRoute = DashboardLayoutTagsImport.update({
  path: '/tags',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

const DashboardLayoutDashboardRoute = DashboardLayoutDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => DashboardLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout': {
      id: '/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof rootRoute
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsImport
      parentRoute: typeof rootRoute
    }
    '/login-register': {
      id: '/login-register'
      path: '/login-register'
      fullPath: '/login-register'
      preLoaderRoute: typeof LoginRegisterImport
      parentRoute: typeof rootRoute
    }
    '/_dashboardLayout/dashboard': {
      id: '/_dashboardLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutDashboardImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/tags': {
      id: '/_dashboardLayout/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof DashboardLayoutTagsImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/_dashboardLayout/upload-expense': {
      id: '/_dashboardLayout/upload-expense'
      path: '/upload-expense'
      fullPath: '/upload-expense'
      preLoaderRoute: typeof DashboardLayoutUploadExpenseImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRoute.addChildren({
    DashboardLayoutDashboardRoute,
    DashboardLayoutTagsRoute,
    DashboardLayoutUploadExpenseRoute,
  }),
  ChartsRoute,
  LoginRegisterRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboardLayout",
        "/charts",
        "/login-register"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dashboardLayout": {
      "filePath": "_dashboardLayout.tsx",
      "children": [
        "/_dashboardLayout/dashboard",
        "/_dashboardLayout/tags",
        "/_dashboardLayout/upload-expense"
      ]
    },
    "/charts": {
      "filePath": "charts.jsx"
    },
    "/login-register": {
      "filePath": "login-register.tsx"
    },
    "/_dashboardLayout/dashboard": {
      "filePath": "_dashboardLayout/dashboard.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/tags": {
      "filePath": "_dashboardLayout/tags.tsx",
      "parent": "/_dashboardLayout"
    },
    "/_dashboardLayout/upload-expense": {
      "filePath": "_dashboardLayout/upload-expense.tsx",
      "parent": "/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
