/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const UploadCsvLazyImport = createFileRoute('/upload-csv')()

// Create/Update Routes

const UploadCsvLazyRoute = UploadCsvLazyImport.update({
  path: '/upload-csv',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/upload-csv.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-csv': {
      id: '/upload-csv'
      path: '/upload-csv'
      fullPath: '/upload-csv'
      preLoaderRoute: typeof UploadCsvLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ UploadCsvLazyRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/upload-csv"
      ]
    },
    "/upload-csv": {
      "filePath": "upload-csv.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
