/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadCsvImport } from './routes/upload-csv'
import { Route as LoginRegisterImport } from './routes/login-register'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UploadCsvRoute = UploadCsvImport.update({
  path: '/upload-csv',
  getParentRoute: () => rootRoute,
} as any)

const LoginRegisterRoute = LoginRegisterImport.update({
  path: '/login-register',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login-register': {
      id: '/login-register'
      path: '/login-register'
      fullPath: '/login-register'
      preLoaderRoute: typeof LoginRegisterImport
      parentRoute: typeof rootRoute
    }
    '/upload-csv': {
      id: '/upload-csv'
      path: '/upload-csv'
      fullPath: '/upload-csv'
      preLoaderRoute: typeof UploadCsvImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRegisterRoute,
  UploadCsvRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login-register",
        "/upload-csv"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login-register": {
      "filePath": "login-register.tsx"
    },
    "/upload-csv": {
      "filePath": "upload-csv.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
